### ISSUE TITLE
General Purpose Mouse support

### ISSUE THREAD

**Issue by zond** [JoelOtter/termloop#10]
GPM [1] provides mouse support for at least Linux terminals. 

Do you think it would be possible to support GPM with termloop? It would enable some nice scenarios :)

1: https://en.m.wikipedia.org/wiki/GPM_(software)

**Comment by JoelOtter** [comment]
Excellent idea. Tagging this as a feature, I think this is a must-have. :smile:

**Comment by zond** [comment]
Excellent! I just hope iOS and Windows has similar features :)

**Comment by JoelOtter** [comment]
Not sure if it's precisely GPM, but mouse clicks are in, in commit 0412ee6. I've tested on OSX, and I imagine they're fine on Linux too - haven't been able to test Windows. Going to mark this closed. Thanks!
