### ISSUE TITLE
Canvas background and foreground colors

### ISSUE THREAD

**Issue by melaurent** [JoelOtter/termloop#11]
I can't choose cell's foreground and background colors when loading canvas from string. Wouldn't it be interesting to add two colors arguments to the function ?

**Comment by JoelOtter** [comment]
Would something like this solve your problem?

```go
e := NewEntityFromCanvas(x, y, CanvasFromString("abcd"))
e.Fill(&Cell{
    Fg: tl.ColorRed,
    Bg: tl.ColorBlue,
})
```

**Comment by melaurent** [comment]
Yes that's what I needed ! Thanks
