### ISSUE TITLE
Screen size before game.Start()

### ISSUE THREAD

**Issue by aquilax** [JoelOtter/termloop#13]
I hit an existential chicken-egg issue. Is there a way to get the screen size before game.Start()? `game.Screen().Size()` returns `0, 0`

**Comment by JoelOtter** [comment]
No, but you should draw relative to the screen boundaries in your Draw method anyway, as otherwise resizes won't get handled correctly.

**Comment by JoelOtter** [comment]
For these types of questions it might be easier to get answers on the Gitter chat. Feel free to @ me there if you're having difficulties. :smiley: 

Going to close this for now as there's no potential code change here - the terminal doesn't get put into curses-mode until `game.Start()` is called, so it doesn't know what size your Screen is at that point.
