### ISSUE TITLE
Update mouse handling

### ISSUE THREAD

**Issue by JoelOtter** [JoelOtter/termloop#25]
Termbox has added support for [additional mouse events](https://github.com/nsf/termbox-go/commit/4aa457c414d0392fb8981c975a0b9fdd3adc4917), including mouse wheel and release detection. 
Support for this should be added to Termloop - however, as these new features are currently not supported on Windows, it might be better to add them to termloop/extras, or simply wait.

**Comment by JoelOtter** [comment]
Looks like Windows support [is in](https://github.com/JoelOtter/termbox-go/commit/9563fa701fa8323f365378b5f6605cefc806ab28).

**Comment by bmatsuo** [comment]
Is there anything blocking this issue now? I would like this. It seems that using the termbox constants in Tick functions works fine for the time being. But it would save people some searching and would avoid the need to convert between the packages' Key types.

**Comment by JoelOtter** [comment]
Nope, nothing blocking - just haven't had a spare moment due to my degree murdering all my time right now. I'll try and get it in ASAP. 😃
