### ISSUE TITLE
Check compatibility with newer Go versions

### ISSUE THREAD

**Issue by JoelOtter** [JoelOtter/termloop#29]
Haven't really tested Termloop with Go 1.7+.

**Comment by aquilax** [comment]
Checked all examples with go1.7.1. Everything looks fine :+1:

**Comment by JoelOtter** [comment]
@aquilax Thanks for the super quick response! Can you check if `Ctrl+C` exits Number Crusher correctly? If so I'll close this ticket. 😄

**Comment by aquilax** [comment]
@JoelOtter Yes, `Ctrl-C` works as expected

**Comment by JoelOtter** [comment]
Awesome.
