### ISSUE TITLE
Some UTF-8 Runes take up more than one position horizontally.

### ISSUE THREAD

**Issue by sagneta** [JoelOtter/termloop#32]
For example, let's assume we decode the following rune for a [TREE](http://apps.timwhitlock.info/unicode/inspect/hex/1F332) and set it into a cell: 

```
				r, _ := utf8.DecodeRuneInString("\xF0\x9F\x8C\xB2")
				cell = tl.Cell{Fg: tl.ColorWhite, Ch: r}

```

What happens is that the true will fill in _two_ spaces horizontally. If you attempt to insert two trees next to one another you will only see the tree on the left. I _think_ this has something to do with the code taking into account the length of the rune in bytes as opposed to the glyph. The later takes up only one location on the screen.

Incidentally I appreciate your work here. Great work. I just wanted you to know. Thanks you!

**Comment by JoelOtter** [comment]
I don't think that's the reason - my guess is it's simply because these characters are greater than standard width, so the terminal overflows them.

Either way, I suspect this is an issue with [Termbox](https://github.com/nsf/termbox-go) itself.

**Comment by sagneta** [comment]
Ok. I'll just close the issue then. Thanks for your work here.
