### ISSUE TITLE
not escaping

### ISSUE THREAD

**Issue by splace** [JoelOtter/termloop#37]
for me, go1.8, this doesn't stop when hitting esc key.

```
package main
import "github.com/JoelOtter/termloop"
func main() {
	g := termloop.NewGame()
	m:=termloop.NewText(0, 0, "<=0=>", termloop.ColorWhite, termloop.ColorBlue)
	g.Screen().AddEntity(m)
	g.Start()
}
```

**Comment by aquilax** [comment]
Exit was changed to `Ctrl-C` https://github.com/JoelOtter/termloop/blob/master/input.go#L14

**Comment by JoelOtter** [comment]
Thanks @aquilax

**Comment by splace** [comment]
i tried ctrl-C, not working for me.(gnome/mate terminal)

don't terminals often intercept ctrl-c for copy/paste?
